# Generated by Django 5.0.1 on 2024-01-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numC', models.IntegerField(default=0)),
                ('date', models.DateField(null=True)),
                ('quantite', models.IntegerField(default=0)),
                ('cout', models.IntegerField(default=0)),
                ('Stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.stock')),
            ],
        ),
    ]
