# Generated by Django 5.0.1 on 2024-01-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_transferdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdetails',
            name='prixVente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
