# Generated by Django 5.0.1 on 2024-01-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_transferdetails_prixvente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferdetails',
            name='prixVente',
        ),
    ]
