# Generated by Django 5.0.1 on 2024-01-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='numC',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
