# Generated by Django 5.0.1 on 2024-01-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_employee_numc'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salairejour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
