# Generated by Django 5.0.1 on 2024-01-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_abcense'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenteDetails2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateVente', models.DateField(null=True)),
                ('quantite', models.IntegerField(null=True)),
                ('prixTotale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('StockCentre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.stockcentre')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.client')),
            ],
        ),
    ]
