# Generated by Django 5.0.1 on 2024-01-23 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_ventedetails2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventedetails2',
            old_name='StockCentre',
            new_name='stockCentre',
        ),
    ]
